### ISSUE TITLE
Plugin generating Exception on Purple 1.20.2

### ISSUE THREAD

**Issue by ThisIsTenou** [Xitee1/DeathLocation#1]
Plugin is generating exceptions 14 seconds after a player has died:
```
[17:56:00 INFO]: MinecraftPlayer was slain by ZombieYou died at -2086 -20 526
[17:56:14 WARN]: [DeathLocation] Task #6 for DeathLocation v1.2 generated an exception
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?]
        at java.util.HashMap$KeyIterator.next(HashMap.java:1620) ~[?:?]
        at de.xite.deathloc.utils.Actionbar.lambda$startActionbarService$0(Actionbar.java:31) ~[DeathLocation-1.2.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.2.jar:git-Purpur-2094]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.2.jar:git-Purpur-2094]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1497) ~[purpur-1.20.2.jar:git-Purpur-2094]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.2.jar:git-Purpur-2094]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[purpur-1.20.2.jar:git-Purpur-2094]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[purpur-1.20.2.jar:git-Purpur-2094]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2094]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```
```
[17:56:31 INFO]: MinecraftPlayer was slain by ZombieYou died at -2086 -20 526
[17:56:45 WARN]: [DeathLocation] Task #6 for DeathLocation v1.2 generated an exception
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?]
        at java.util.HashMap$KeyIterator.next(HashMap.java:1620) ~[?:?]
        at de.xite.deathloc.utils.Actionbar.lambda$startActionbarService$0(Actionbar.java:31) ~[DeathLocation-1.2.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.2.jar:git-Purpur-2094]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.2.jar:git-Purpur-2094]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1497) ~[purpur-1.20.2.jar:git-Purpur-2094]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.2.jar:git-Purpur-2094]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[purpur-1.20.2.jar:git-Purpur-2094]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[purpur-1.20.2.jar:git-Purpur-2094]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2094]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

Current plugin config:
```
types:
  chat-message: true
  actionbar: true
  title: false

actionbar:
  timeout: 15 # Duration to show the actionbar for (in seconds)

allPlayers: true

message:
  append: true # The location will be appended to the existing death message (only chat). Warning: Every player will see the location, like the "allPlayers" option!
  message: '&4You died at &b%x %y %z' # Placeholders: %player, %x, %y, %z

update:
  notification: true

debug: false
```

Due to the matching timeout, I assume this is an issue with the actionbar. It did not show at all.

**Comment by Xitee1** [comment]
Will fix it soon
